<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\FlowDeck.Core\FlowDeck.Core.csproj" />
    <ProjectReference Include="..\FlowDeck.Persistence.EntityFrameworkCore\FlowDeck.Persistence.EntityFrameworkCore.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
