/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/workflows/{definitionId}/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts a new instance of a workflow definition. */
        post: operations["StartWorkflowInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the workflow definitions this host has registered. */
        get: operations["ListWorkflowDefinitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{definitionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describes one definition: the steps it declares and the branches leaving them. */
        get: operations["GetWorkflowDefinition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a single workflow instance. */
        get: operations["GetWorkflowInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists workflow instances, newest first. */
        get: operations["ListWorkflowInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stops a workflow instance permanently. */
        post: operations["CancelWorkflowInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/bulk/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancels every instance matching a filter, reporting each one. */
        post: operations["BulkCancelWorkflowInstances"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/bulk/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retries every finished instance matching a filter, reporting each one. */
        post: operations["BulkRetryWorkflowInstances"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Asks a running instance to park at its next step boundary. */
        post: operations["SuspendWorkflowInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts a new instance repeating a finished one from the beginning. */
        post: operations["RetryWorkflowInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}/retry-from-failed-step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts a new instance continuing a failed one from the step that broke. */
        post: operations["RetryWorkflowInstanceFromFailedStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}/cancel-and-roll-back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stops a workflow instance and unwinds the work it had completed. */
        post: operations["CancelAndRollBackWorkflowInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continues a suspended workflow instance. */
        post: operations["ResumeWorkflowInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reads an instance's execution history, in order. */
        get: operations["GetWorkflowInstanceHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BulkActionReport: {
            /** Format: int32 */
            attempted: number | string;
            /** Format: int32 */
            succeeded: number | string;
            /** Format: int32 */
            failed: number | string;
            truncated: boolean;
            results: components["schemas"]["BulkActionResult"][];
        };
        BulkActionResult: {
            /** Format: uuid */
            instanceId: string;
            succeeded: boolean;
            error: null | string;
            /** Format: uuid */
            newInstanceId: null | string;
        };
        InstancePage: {
            items: components["schemas"]["InstanceResponse"][];
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        InstanceResponse: {
            /** Format: uuid */
            id: string;
            definitionId: string;
            /** Format: int32 */
            definitionVersion: number | string;
            status: components["schemas"]["InstanceStatus"];
            /** Format: int32 */
            currentStepIndex: number | string;
            currentStepName: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: null | string;
            failedStepName: null | string;
            errorType: null | string;
            errorMessage: null | string;
            ownerNodeId: null | string;
            /** Format: date-time */
            leaseExpiresAt: null | string;
            /** Format: uuid */
            retriedFromInstanceId: null | string;
            awaitingRecovery?: boolean;
        };
        /** @enum {unknown} */
        InstanceStatus: "Running" | "Suspended" | "Completed" | "Failed" | "Cancelled" | "Compensated" | "CompensationFailed";
        StartInstanceResponse: {
            /** Format: uuid */
            instanceId: string;
            status: components["schemas"]["InstanceStatus"];
        };
        StepHistoryResponse: {
            /** Format: int32 */
            sequence: number | string;
            stepName: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            /** Format: double */
            durationMs: number | string;
            status: components["schemas"]["StepStatus"];
            /** Format: int32 */
            attempt: number | string;
            errorType: null | string;
            errorMessage: null | string;
        };
        /** @enum {unknown} */
        StepStatus: "Success" | "Failed";
        WorkflowBranchResponse: {
            name: string;
            isConditional: boolean;
            isParallel: boolean;
            steps: components["schemas"]["WorkflowStepResponse"][];
        };
        WorkflowDefinitionDetailResponse: {
            id: string;
            /** Format: int32 */
            version: number | string;
            inputTypeName: null | string;
            steps: components["schemas"]["WorkflowStepResponse"][];
        };
        WorkflowDefinitionResponse: {
            id: string;
            /** Format: int32 */
            version: number | string;
            inputTypeName: null | string;
            /** Format: int32 */
            activeInstances: number | string;
        };
        WorkflowStepResponse: {
            name: string;
            /** Format: int32 */
            maxAttempts: number | string;
            hasCompensation: boolean;
            branches: components["schemas"]["WorkflowBranchResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    StartWorkflowInstance: {
        parameters: {
            query?: {
                version?: number | string;
            };
            header?: never;
            path: {
                definitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartInstanceResponse"];
                };
            };
        };
    };
    ListWorkflowDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionResponse"][];
                };
            };
        };
    };
    GetWorkflowDefinition: {
        parameters: {
            query?: {
                version?: number | string;
            };
            header?: never;
            path: {
                definitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionDetailResponse"];
                };
            };
        };
    };
    GetWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
        };
    };
    ListWorkflowInstances: {
        parameters: {
            query?: {
                status?: components["schemas"]["InstanceStatus"];
                definitionId?: string;
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstancePage"];
                };
            };
        };
    };
    CancelWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
        };
    };
    BulkCancelWorkflowInstances: {
        parameters: {
            query?: {
                status?: components["schemas"]["InstanceStatus"];
                definitionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkActionReport"];
                };
            };
        };
    };
    BulkRetryWorkflowInstances: {
        parameters: {
            query?: {
                status?: components["schemas"]["InstanceStatus"];
                definitionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkActionReport"];
                };
            };
        };
    };
    SuspendWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
        };
    };
    RetryWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
        };
    };
    RetryWorkflowInstanceFromFailedStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
        };
    };
    CancelAndRollBackWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
        };
    };
    ResumeWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
        };
    };
    GetWorkflowInstanceHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepHistoryResponse"][];
                };
            };
        };
    };
}
