/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/workflows/{definitionId}/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Starts a new instance of a workflow definition. */
        post: operations["StartWorkflowInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists the workflow definitions this host has registered. */
        get: operations["ListWorkflowDefinitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a single workflow instance. */
        get: operations["GetWorkflowInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists workflow instances, newest first. */
        get: operations["ListWorkflowInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stops a workflow instance permanently. */
        post: operations["CancelWorkflowInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instanceId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reads an instance's execution history, in order. */
        get: operations["GetWorkflowInstanceHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InstancePage: {
            items: components["schemas"]["InstanceResponse"][];
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        InstanceResponse: {
            /** Format: uuid */
            id: string;
            definitionId: string;
            /** Format: int32 */
            definitionVersion: number | string;
            status: components["schemas"]["InstanceStatus"];
            /** Format: int32 */
            currentStepIndex: number | string;
            currentStepName: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: null | string;
            failedStepName: null | string;
            errorType: null | string;
            errorMessage: null | string;
            ownerNodeId: null | string;
            /** Format: date-time */
            leaseExpiresAt: null | string;
            awaitingRecovery?: boolean;
        };
        /** @enum {unknown} */
        InstanceStatus: "Running" | "Suspended" | "Completed" | "Failed" | "Cancelled" | "Compensated" | "CompensationFailed";
        StartInstanceResponse: {
            /** Format: uuid */
            instanceId: string;
            status: components["schemas"]["InstanceStatus"];
        };
        StepHistoryResponse: {
            /** Format: int32 */
            sequence: number | string;
            stepName: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            /** Format: double */
            durationMs: number | string;
            status: components["schemas"]["StepStatus"];
            /** Format: int32 */
            attempt: number | string;
            errorType: null | string;
            errorMessage: null | string;
        };
        /** @enum {unknown} */
        StepStatus: "Success" | "Failed";
        WorkflowDefinitionResponse: {
            id: string;
            /** Format: int32 */
            version: number | string;
            inputTypeName: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    StartWorkflowInstance: {
        parameters: {
            query?: {
                version?: number | string;
            };
            header?: never;
            path: {
                definitionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartInstanceResponse"];
                };
            };
        };
    };
    ListWorkflowDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinitionResponse"][];
                };
            };
        };
    };
    GetWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
        };
    };
    ListWorkflowInstances: {
        parameters: {
            query?: {
                status?: components["schemas"]["InstanceStatus"];
                definitionId?: string;
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstancePage"];
                };
            };
        };
    };
    CancelWorkflowInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
        };
    };
    GetWorkflowInstanceHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepHistoryResponse"][];
                };
            };
        };
    };
}
